title: Struktur Data - Moh. Ghufron
author: Moh. Ghufron
logo: images/logo.png

execute:
  execute_notebooks: off

parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - colon_fence
    - substitution
    - linkify
    - html_admonition
    - html_image

sphinx:
  config:
    html_allow_unicode: true
    html_force_compact_title: false
    html_static_path: ["images"]

html:
  use_issues_button: false
  use_repository_button: false